language: objective-c #1
osx_image:  xcode9.1 #2
#xcode_workspace: Awesome.xcworkspace #3
#xcode_scheme: Awesome #4
#xcode_sdk: iphonesimulator9.3 #5

script:
    - xcodebuild clean test -workspace Awesome.xcworkspace -scheme Awesome -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

notifications: 
  email:
    recipients:
      - artak1984@gmail.com

    on_success: change
    on_failure: always