language: objective-c

before_install:
    - brew update
#    - brew install xctool


#script: xctool -workspace Awesome.xcworkspace -scheme AwesomeTest test

xcode_workspace: Awesome.xcworkspace
xcode_scheme: AwesomeTests
podfile: Podfile
os: ios
osx_image: xcode9.1
xcode_sdk: iphonesimulator9.0

