language: objective-c

#before_install:
#    - brew update
#    - brew install xctool


#script: xctool -workspace Awesome.xcworkspace -scheme AwesomeTest test

xcode_workspace: Awesome/Awesome.xcworkspace
xcode_scheme: AwesomeTests
podfile: Awesome/Podfile
os: ios
osx_image: xcode9.0
xcode_sdk: iphonesimulator9.3

