language: objective-c #1
osx_image:  xcode9.1 #2
xcode_workspace: Awesome.xcworkspace #3
xcode_scheme: Awesome #4
xcode_sdk: iphonesimulator9.3 #5


notifications: 
  email:
    recipients:
      - artak1984@gmail.com

    on_success: change
    on_failure: always