language: objective-c

before_install:
    - brew update
    - brew install xctool
    - sudo gem install xcpretty
#install: 
#   - pod update
script:
    - open -b com.apple.iphonesimulator
    - xcodebuild -workspace Awesome/Awesome.xcworkspace -scheme 'Awesome' -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' -sdk iphonesimulator build test > build.log && exit ${PIPESTATUS[0]}

#after_failure:
#  - tail -n 500 build.log

xcode_workspace: Awesome.xcworkspace
xcode_scheme: Awesome
#podfile: Podfile
#os: ios
osx_image: xcode9.1
xcode_sdk: iphonesimulator9.3

